# Pull base image.
FROM frolvlad/alpine-oraclejdk8:latest

VOLUME /tmp

ADD gs-spring-boot-docker-0.1.0.jar oauth.1.3.3.RELEASE.jar
RUN sh -c 'touch /oauth.1.3.3.RELEASE.jar'
ENTRYPOINT ["java", "-Djava.security.egd-file:/dev/./urandom","-jar","/oauth.1.3.3.RELEASE.jar"]
